[project]
name = "odoo-addons-oca-server-env"
version = "18.0.20241004.0"
dependencies = [
    "odoo-addon-server_environment==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
